### ISSUE TITLE
configuration instructions

### ISSUE THREAD

**Issue by pasunboneleve** [dssg/police-eis#244]
Hi, all.

We're interested in trialling this project to be used by the state government in Victoria, Australia. 

I have this project in a virtual machine. l was expecting that I would just need to create dummy data, but I was wrong. You included your data schema, but not the relevant configuration files or documentation on creating these so that the software calls the database containing the schema.

Would you be able to provide some guidance?

**Comment by jtwalsh0** [comment]
Hi @dmvianna, if you're starting from scratch, I'd recommend using [triage](http://github.com/dssg/triage). Triage developed out of this police code and added some functionality police-eis is missing. [This repo](https://github.com/dssg/benchmark) demonstrates a triage police implementation.

(Anything else we should add, @k1aus?)

**Comment by pasunboneleve** [comment]
Thanks! Looking through your repo I found what I needed, which is not **what** (police-eis, benchmark), but **how** ([dirtyduck](https://github.com/dssg/dirtyduck)). Thank you so much for creating these tutorials!
