### ISSUE TITLE
Rewrite officer_labeller() for staging tables

### ISSUE THREAD

**Issue by redshiftzero** [dssg/police-eis#9]
`officer_labeller()` is generally a mess. In addition, it needs to be rewritten for the staging tables (primarily for the IA table). It should preserve an option for including or excluding officers that have not been investigated in the dataset.

**Comment by hinnefe2** [comment]
I changed the department config file a bit for this:
- the `labelling` options are now:  
    - `include_all_active` : include all officers who show up in arrests, stops, and traffic stops
    - `include_all_employed`: include all officers who were employed then

- I added `events_hub` to the list of top level tables

**Comment by hinnefe2** [comment]
Done and merged.
